client_id = "f7dfecdb8cb05f8874cd0db742121578"
name = "MoovExpress"
application_url = "https://moovexpress.com/api/integrazioni/shopify/enter"
embedded = false

[access_scopes]
scopes = "read_orders,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://moovexpress.com/api/integrazioni/shopify/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://moovexpress.com/api/integrazioni/shopify/webhooks/compliance"
