// Elenco COMPLETO dei paesi del mondo (ISO 3166-1 alpha-2 + nome italiano), per la tendina
// destinatario delle spedizioni. Prima la tendina era hardcoded coi soli ~28 paesi UE/europei: non
// si poteva selezionare San Marino, Svizzera, USA e tutto l'extra-UE. Italia in testa (default),
// il resto in ordine alfabetico italiano. Un solo posto, usato da cliente e master.
export type Paese = { code: string; nome: string }

export const PAESI_MONDO: Paese[] = [
  { code: 'IT', nome: 'Italia' },
  { code: 'AF', nome: 'Afghanistan' },
  { code: 'AL', nome: 'Albania' },
  { code: 'DZ', nome: 'Algeria' },
  { code: 'AD', nome: 'Andorra' },
  { code: 'AO', nome: 'Angola' },
  { code: 'AI', nome: 'Anguilla' },
  { code: 'AG', nome: 'Antigua e Barbuda' },
  { code: 'SA', nome: 'Arabia Saudita' },
  { code: 'AR', nome: 'Argentina' },
  { code: 'AM', nome: 'Armenia' },
  { code: 'AW', nome: 'Aruba' },
  { code: 'AU', nome: 'Australia' },
  { code: 'AT', nome: 'Austria' },
  { code: 'AZ', nome: 'Azerbaigian' },
  { code: 'BS', nome: 'Bahamas' },
  { code: 'BH', nome: 'Bahrein' },
  { code: 'BD', nome: 'Bangladesh' },
  { code: 'BB', nome: 'Barbados' },
  { code: 'BE', nome: 'Belgio' },
  { code: 'BZ', nome: 'Belize' },
  { code: 'BJ', nome: 'Benin' },
  { code: 'BM', nome: 'Bermuda' },
  { code: 'BT', nome: 'Bhutan' },
  { code: 'BY', nome: 'Bielorussia' },
  { code: 'BO', nome: 'Bolivia' },
  { code: 'BA', nome: 'Bosnia ed Erzegovina' },
  { code: 'BW', nome: 'Botswana' },
  { code: 'BR', nome: 'Brasile' },
  { code: 'BN', nome: 'Brunei' },
  { code: 'BG', nome: 'Bulgaria' },
  { code: 'BF', nome: 'Burkina Faso' },
  { code: 'BI', nome: 'Burundi' },
  { code: 'KH', nome: 'Cambogia' },
  { code: 'CM', nome: 'Camerun' },
  { code: 'CA', nome: 'Canada' },
  { code: 'CV', nome: 'Capo Verde' },
  { code: 'TD', nome: 'Ciad' },
  { code: 'CL', nome: 'Cile' },
  { code: 'CN', nome: 'Cina' },
  { code: 'CY', nome: 'Cipro' },
  { code: 'VA', nome: 'Città del Vaticano' },
  { code: 'CO', nome: 'Colombia' },
  { code: 'KM', nome: 'Comore' },
  { code: 'CG', nome: 'Congo' },
  { code: 'CD', nome: 'Congo (Rep. Dem.)' },
  { code: 'KP', nome: 'Corea del Nord' },
  { code: 'KR', nome: 'Corea del Sud' },
  { code: 'CI', nome: "Costa d'Avorio" },
  { code: 'CR', nome: 'Costa Rica' },
  { code: 'HR', nome: 'Croazia' },
  { code: 'CU', nome: 'Cuba' },
  { code: 'CW', nome: 'Curaçao' },
  { code: 'DK', nome: 'Danimarca' },
  { code: 'DM', nome: 'Dominica' },
  { code: 'EC', nome: 'Ecuador' },
  { code: 'EG', nome: 'Egitto' },
  { code: 'SV', nome: 'El Salvador' },
  { code: 'AE', nome: 'Emirati Arabi Uniti' },
  { code: 'ER', nome: 'Eritrea' },
  { code: 'EE', nome: 'Estonia' },
  { code: 'SZ', nome: 'Eswatini' },
  { code: 'ET', nome: 'Etiopia' },
  { code: 'FJ', nome: 'Figi' },
  { code: 'PH', nome: 'Filippine' },
  { code: 'FI', nome: 'Finlandia' },
  { code: 'FR', nome: 'Francia' },
  { code: 'GA', nome: 'Gabon' },
  { code: 'GM', nome: 'Gambia' },
  { code: 'GE', nome: 'Georgia' },
  { code: 'DE', nome: 'Germania' },
  { code: 'GH', nome: 'Ghana' },
  { code: 'JM', nome: 'Giamaica' },
  { code: 'JP', nome: 'Giappone' },
  { code: 'GI', nome: 'Gibilterra' },
  { code: 'DJ', nome: 'Gibuti' },
  { code: 'JO', nome: 'Giordania' },
  { code: 'GR', nome: 'Grecia' },
  { code: 'GD', nome: 'Grenada' },
  { code: 'GL', nome: 'Groenlandia' },
  { code: 'GP', nome: 'Guadalupa' },
  { code: 'GU', nome: 'Guam' },
  { code: 'GT', nome: 'Guatemala' },
  { code: 'GG', nome: 'Guernsey' },
  { code: 'GN', nome: 'Guinea' },
  { code: 'GW', nome: 'Guinea-Bissau' },
  { code: 'GQ', nome: 'Guinea Equatoriale' },
  { code: 'GF', nome: 'Guyana francese' },
  { code: 'GY', nome: 'Guyana' },
  { code: 'HT', nome: 'Haiti' },
  { code: 'HN', nome: 'Honduras' },
  { code: 'HK', nome: 'Hong Kong' },
  { code: 'IN', nome: 'India' },
  { code: 'ID', nome: 'Indonesia' },
  { code: 'IR', nome: 'Iran' },
  { code: 'IQ', nome: 'Iraq' },
  { code: 'IE', nome: 'Irlanda' },
  { code: 'IS', nome: 'Islanda' },
  { code: 'BV', nome: 'Isola Bouvet' },
  { code: 'IM', nome: 'Isola di Man' },
  { code: 'KY', nome: 'Isole Cayman' },
  { code: 'CK', nome: 'Isole Cook' },
  { code: 'FO', nome: 'Isole Fær Øer' },
  { code: 'FK', nome: 'Isole Falkland' },
  { code: 'MP', nome: 'Isole Marianne Settentrionali' },
  { code: 'MH', nome: 'Isole Marshall' },
  { code: 'SB', nome: 'Isole Salomone' },
  { code: 'TC', nome: 'Isole Turks e Caicos' },
  { code: 'VG', nome: 'Isole Vergini Britanniche' },
  { code: 'VI', nome: 'Isole Vergini Americane' },
  { code: 'IL', nome: 'Israele' },
  { code: 'JE', nome: 'Jersey' },
  { code: 'KZ', nome: 'Kazakistan' },
  { code: 'KE', nome: 'Kenya' },
  { code: 'KG', nome: 'Kirghizistan' },
  { code: 'KI', nome: 'Kiribati' },
  { code: 'XK', nome: 'Kosovo' },
  { code: 'KW', nome: 'Kuwait' },
  { code: 'LA', nome: 'Laos' },
  { code: 'LS', nome: 'Lesotho' },
  { code: 'LV', nome: 'Lettonia' },
  { code: 'LB', nome: 'Libano' },
  { code: 'LR', nome: 'Liberia' },
  { code: 'LY', nome: 'Libia' },
  { code: 'LI', nome: 'Liechtenstein' },
  { code: 'LT', nome: 'Lituania' },
  { code: 'LU', nome: 'Lussemburgo' },
  { code: 'MO', nome: 'Macao' },
  { code: 'MK', nome: 'Macedonia del Nord' },
  { code: 'MG', nome: 'Madagascar' },
  { code: 'MW', nome: 'Malawi' },
  { code: 'MY', nome: 'Malaysia' },
  { code: 'MV', nome: 'Maldive' },
  { code: 'ML', nome: 'Mali' },
  { code: 'MT', nome: 'Malta' },
  { code: 'MA', nome: 'Marocco' },
  { code: 'MQ', nome: 'Martinica' },
  { code: 'MR', nome: 'Mauritania' },
  { code: 'MU', nome: 'Mauritius' },
  { code: 'YT', nome: 'Mayotte' },
  { code: 'MX', nome: 'Messico' },
  { code: 'FM', nome: 'Micronesia' },
  { code: 'MD', nome: 'Moldova' },
  { code: 'MC', nome: 'Monaco' },
  { code: 'MN', nome: 'Mongolia' },
  { code: 'ME', nome: 'Montenegro' },
  { code: 'MS', nome: 'Montserrat' },
  { code: 'MZ', nome: 'Mozambico' },
  { code: 'MM', nome: 'Myanmar (Birmania)' },
  { code: 'NA', nome: 'Namibia' },
  { code: 'NR', nome: 'Nauru' },
  { code: 'NP', nome: 'Nepal' },
  { code: 'NI', nome: 'Nicaragua' },
  { code: 'NE', nome: 'Niger' },
  { code: 'NG', nome: 'Nigeria' },
  { code: 'NU', nome: 'Niue' },
  { code: 'NO', nome: 'Norvegia' },
  { code: 'NC', nome: 'Nuova Caledonia' },
  { code: 'NZ', nome: 'Nuova Zelanda' },
  { code: 'OM', nome: 'Oman' },
  { code: 'NL', nome: 'Paesi Bassi' },
  { code: 'PK', nome: 'Pakistan' },
  { code: 'PW', nome: 'Palau' },
  { code: 'PS', nome: 'Palestina' },
  { code: 'PA', nome: 'Panama' },
  { code: 'PG', nome: 'Papua Nuova Guinea' },
  { code: 'PY', nome: 'Paraguay' },
  { code: 'PE', nome: 'Perù' },
  { code: 'PF', nome: 'Polinesia francese' },
  { code: 'PL', nome: 'Polonia' },
  { code: 'PT', nome: 'Portogallo' },
  { code: 'PR', nome: 'Porto Rico' },
  { code: 'QA', nome: 'Qatar' },
  { code: 'GB', nome: 'Regno Unito' },
  { code: 'CZ', nome: 'Repubblica Ceca' },
  { code: 'CF', nome: 'Repubblica Centrafricana' },
  { code: 'DO', nome: 'Repubblica Dominicana' },
  { code: 'RE', nome: 'Riunione' },
  { code: 'RO', nome: 'Romania' },
  { code: 'RW', nome: 'Ruanda' },
  { code: 'RU', nome: 'Russia' },
  { code: 'EH', nome: 'Sahara Occidentale' },
  { code: 'KN', nome: 'Saint Kitts e Nevis' },
  { code: 'LC', nome: 'Saint Lucia' },
  { code: 'VC', nome: 'Saint Vincent e Grenadine' },
  { code: 'WS', nome: 'Samoa' },
  { code: 'AS', nome: 'Samoa Americane' },
  { code: 'SM', nome: 'San Marino' },
  { code: 'SH', nome: "Sant'Elena" },
  { code: 'ST', nome: 'São Tomé e Príncipe' },
  { code: 'SN', nome: 'Senegal' },
  { code: 'RS', nome: 'Serbia' },
  { code: 'SC', nome: 'Seychelles' },
  { code: 'SL', nome: 'Sierra Leone' },
  { code: 'SG', nome: 'Singapore' },
  { code: 'SX', nome: 'Sint Maarten' },
  { code: 'SY', nome: 'Siria' },
  { code: 'SK', nome: 'Slovacchia' },
  { code: 'SI', nome: 'Slovenia' },
  { code: 'SO', nome: 'Somalia' },
  { code: 'ES', nome: 'Spagna' },
  { code: 'LK', nome: 'Sri Lanka' },
  { code: 'US', nome: 'Stati Uniti' },
  { code: 'ZA', nome: 'Sudafrica' },
  { code: 'SD', nome: 'Sudan' },
  { code: 'SS', nome: 'Sudan del Sud' },
  { code: 'SR', nome: 'Suriname' },
  { code: 'SE', nome: 'Svezia' },
  { code: 'CH', nome: 'Svizzera' },
  { code: 'TJ', nome: 'Tagikistan' },
  { code: 'TW', nome: 'Taiwan' },
  { code: 'TZ', nome: 'Tanzania' },
  { code: 'TH', nome: 'Thailandia' },
  { code: 'TL', nome: 'Timor Est' },
  { code: 'TG', nome: 'Togo' },
  { code: 'TK', nome: 'Tokelau' },
  { code: 'TO', nome: 'Tonga' },
  { code: 'TT', nome: 'Trinidad e Tobago' },
  { code: 'TN', nome: 'Tunisia' },
  { code: 'TR', nome: 'Turchia' },
  { code: 'TM', nome: 'Turkmenistan' },
  { code: 'TV', nome: 'Tuvalu' },
  { code: 'UA', nome: 'Ucraina' },
  { code: 'UG', nome: 'Uganda' },
  { code: 'HU', nome: 'Ungheria' },
  { code: 'UY', nome: 'Uruguay' },
  { code: 'UZ', nome: 'Uzbekistan' },
  { code: 'VU', nome: 'Vanuatu' },
  { code: 'VE', nome: 'Venezuela' },
  { code: 'VN', nome: 'Vietnam' },
  { code: 'WF', nome: 'Wallis e Futuna' },
  { code: 'YE', nome: 'Yemen' },
  { code: 'ZM', nome: 'Zambia' },
  { code: 'ZW', nome: 'Zimbabwe' },
]
